
export const TODO_TOGGLE_CREATE_BTN = 'TODO_TOGGLE_CREATE_BTN'

export const TODO_TOGGLE_ISFETCHING_LIST = 'TODO_TOGGLE_ISFETCHING_LIST'
export const TODO_GETLIST_SUCCESS = 'TODO_GETLIST_SUCCESS'
export const TODO_GETLIST_ERROR = 'TODO_GETLIST_ERROR'

export const TODO_TOGGLE_ISCREATING = 'TODO_TOGGLE_ISCREATING'
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS'
export const TODO_CREATE_ERROR = 'TODO_CREATE_ERROR'

export const TODO_TOGGLE_ISFETCHING_TASK = 'TODO_TOGGLE_ISFETCHING_TASK'
export const TODO_GETTASK_SUCCESS = 'TODO_GETTASK_SUCCESS'
export const TODO_GETTASK_ERROR = 'TODO_GETTASK_ERROR'
export const TODO_NULLIFY_FETCHEDTASK = 'TODO_NULLIFY_FETCHEDTASK'

export const TODO_TOGGLE_ISUPDATING_TASK = 'TODO_TOGGLE_ISUPDATING_TASK'
export const TODO_UPDATETASK_SUCCESS = 'TODO_UPDATETASK_SUCCESS'
export const TODO_UPDATETASK_ERROR = 'TODO_UPDATETASK_ERROR'

export const TODO_TOGGLE_ISDELETING_TASK = 'TODO_TOGGLE_ISDELETING_TASK'
export const TODO_DELETETASK_SUCCESS = 'TODO_DELETETASK_SUCCESS'
export const TODO_DELETETASK_ERROR = 'TODO_DELETETASK_ERROR'


